// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// @ts-nocheck
/*
  Prisma 7 configuration placeholder.
  This project is on Prisma 6.x, so this file is intentionally disabled
  to avoid TypeScript errors during builds.
*/

export {};
